# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jogo_da_velha.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jogo_da_velha(object):
    def setupUi(self, jogo_da_velha):
        jogo_da_velha.setObjectName("jogo_da_velha")
        jogo_da_velha.resize(298, 300)
        jogo_da_velha.setMaximumSize(QtCore.QSize(300, 300))
        self.centralwidget = QtWidgets.QWidget(jogo_da_velha)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(0, 40, 100, 71))
        self.btn_1.setText("")
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(100, 40, 100, 71))
        self.btn_2.setText("")
        self.btn_2.setObjectName("btn_2")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(200, 40, 100, 71))
        self.btn_3.setText("")
        self.btn_3.setObjectName("btn_3")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(0, 110, 100, 71))
        self.btn_4.setText("")
        self.btn_4.setObjectName("btn_4")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(200, 110, 100, 71))
        self.btn_6.setText("")
        self.btn_6.setObjectName("btn_6")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(100, 110, 100, 71))
        self.btn_5.setText("")
        self.btn_5.setObjectName("btn_5")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(0, 180, 100, 71))
        self.btn_7.setText("")
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(100, 180, 100, 71))
        self.btn_8.setText("")
        self.btn_8.setObjectName("btn_8")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(200, 180, 100, 71))
        self.btn_9.setText("")
        self.btn_9.setObjectName("btn_9")
        self.label_superior = QtWidgets.QLabel(self.centralwidget)
        self.label_superior.setGeometry(QtCore.QRect(10, 0, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_superior.setFont(font)
        self.label_superior.setObjectName("label_superior")
        self.label_inferior = QtWidgets.QLabel(self.centralwidget)
        self.label_inferior.setGeometry(QtCore.QRect(10, 250, 191, 41))
        self.label_inferior.setObjectName("label_inferior")
        self.btn_reset = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reset.setGeometry(QtCore.QRect(200, 250, 100, 51))
        self.btn_reset.setObjectName("btn_reset")
        jogo_da_velha.setCentralWidget(self.centralwidget)
        self.actionOpen = QtWidgets.QAction(jogo_da_velha)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(jogo_da_velha)
        self.actionClose.setObjectName("actionClose")
        self.actionSettings = QtWidgets.QAction(jogo_da_velha)
        self.actionSettings.setObjectName("actionSettings")

        self.retranslateUi(jogo_da_velha)
        QtCore.QMetaObject.connectSlotsByName(jogo_da_velha)
        jogo_da_velha.setTabOrder(self.btn_1, self.btn_2)
        jogo_da_velha.setTabOrder(self.btn_2, self.btn_3)
        jogo_da_velha.setTabOrder(self.btn_3, self.btn_4)
        jogo_da_velha.setTabOrder(self.btn_4, self.btn_5)
        jogo_da_velha.setTabOrder(self.btn_5, self.btn_6)
        jogo_da_velha.setTabOrder(self.btn_6, self.btn_7)
        jogo_da_velha.setTabOrder(self.btn_7, self.btn_8)
        jogo_da_velha.setTabOrder(self.btn_8, self.btn_9)
        jogo_da_velha.setTabOrder(self.btn_9, self.btn_reset)

    def retranslateUi(self, jogo_da_velha):
        _translate = QtCore.QCoreApplication.translate
        jogo_da_velha.setWindowTitle(_translate("jogo_da_velha", "Jogo de Velha"))
        self.label_superior.setText(_translate("jogo_da_velha", "BEM VINDO AO JOGO DA VELHA!"))
        self.label_inferior.setText(_translate("jogo_da_velha", "PONTUAÇÃO X: \n\n PONTUAÇÃO O:"))
        self.btn_reset.setText(_translate("jogo_da_velha", "RESET"))
        self.actionOpen.setText(_translate("jogo_da_velha", "Open"))
        self.actionClose.setText(_translate("jogo_da_velha", "Close"))
        self.actionSettings.setText(_translate("jogo_da_velha", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    jogo_da_velha = QtWidgets.QMainWindow()
    ui = Ui_jogo_da_velha()
    ui.setupUi(jogo_da_velha)
    jogo_da_velha.show()
    sys.exit(app.exec_())
